# These are not yet configured.
# Remove the `#` comments below to enable.
#
# github: # Replace with GitHub sponsors usernames
# patreon: # Replace with Patreon username
# open_collective: # Replace with Open Collective username
# ko_fi: # Replace with Ko-fi username
# tidelift: # Replace with Tidelift platform name
# custom: # Replace with URLs
