"""LLM-based code generation from evolved prompts.

Supports OpenAI-compatible APIs (OpenAI, Mistral, local LLMs via Ollama).
Configure via environment variables — never hardcode API keys.
"""

import os
import re
from pathlib import Path

_openai_client = None

DEFAULT_BASE_URL = os.environ.get(
    "LLM_BASE_URL",
    "https://api.mistral.ai/v1",
)
DEFAULT_MODEL = os.environ.get("LLM_MODEL", "mistral-large-latest")


def _get_client():
    global _openai_client
    if _openai_client is None:
        from openai import OpenAI
        api_key = os.environ.get("LLM_API_KEY")
        if not api_key:
            raise ValueError(
                "LLM_API_KEY environment variable not set. "
                "Export it or set it in your .env file."
            )
        _openai_client = OpenAI(
            api_key=api_key,
            base_url=DEFAULT_BASE_URL,
        )
    return _openai_client


TEMPLATES = [
    {
        "main.py": '''"""
Modular application entry point.
"""
import sys
import json


def main():
    print("Hello from grounded evolution project")


if __name__ == "__main__":
    main()
''',
        "test_main.py": '''"""Tests for main module."""
from main import main


def test_main_runs():
    assert callable(main)
''',
        "requirements.txt": "pytest\n",
        "README.md": "# Generated Project\n\nAuto-generated by Grounded Evolution System\n",
    },
    {
        "main.py": '''"""
Simple REST API server stub.
"""
import json
from http.server import HTTPServer, BaseHTTPRequestHandler


class Handler(BaseHTTPRequestHandler):
    def do_GET(self):
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.end_headers()
        self.wfile.write(json.dumps({"status": "ok", "endpoint": self.path}).encode())


def create_server(port=8000):
    return HTTPServer(("", port), Handler)


if __name__ == "__main__":
    server = create_server()
    print(f"Server running on port 8000")
    server.serve_forever()
''',
        "test_server.py": '''"""Tests for server module."""
from main import create_server


def test_create_server():
    server = create_server(port=0)
    assert server is not None
    server.server_close()
''',
        "requirements.txt": "pytest\n",
        "README.md": "# API Server\n\nA simple HTTP API server\n",
    },
    {
        "main.py": '''"""
CLI task manager.
"""
import argparse
import json
import os

TASKS_FILE = "tasks.json"


def load_tasks():
    if os.path.exists(TASKS_FILE):
        with open(TASKS_FILE) as f:
            return json.load(f)
    return []


def add_task(description):
    tasks = load_tasks()
    tasks.append({"id": len(tasks) + 1, "description": description, "done": False})
    with open(TASKS_FILE, "w") as f:
        json.dump(tasks, f, indent=2)
    print(f"Added task: {description}")


def list_tasks():
    tasks = load_tasks()
    for t in tasks:
        status = "✓" if t["done"] else " "
        print(f"[{status}] {t['id']}: {t['description']}")


def main():
    parser = argparse.ArgumentParser(description="Task Manager")
    parser.add_argument("command", choices=["add", "list"])
    parser.add_argument("args", nargs="*")
    args = parser.parse_args()
    if args.command == "add" and args.args:
        add_task(" ".join(args.args))
    elif args.command == "list":
        list_tasks()


if __name__ == "__main__":
    main()
''',
        "test_cli.py": '''"""Tests for CLI task manager."""
from main import add_task, list_tasks, load_tasks
import os


def test_add_and_load():
    if os.path.exists("tasks.json"):
        os.remove("tasks.json")
    add_task("test task")
    tasks = load_tasks()
    assert len(tasks) == 1
    if os.path.exists("tasks.json"):
        os.remove("tasks.json")
''',
        "requirements.txt": "pytest\n",
        "README.md": "# CLI Task Manager\n\nA simple task manager CLI\n",
    },
]


def generate_code(prompt, model=None, temperature=None):
    client = _get_client()
    response = client.chat.completions.create(
        model=model or "mistral-large-latest",
        messages=[
            {
                "role": "system",
                "content": "You are an autonomous software architect. Generate clean executable Python projects. Output each file in a markdown code block with the filename as the language tag (e.g. ```main.py). Include a README.md and requirements.txt.",
            },
            {"role": "user", "content": prompt},
        ],
        temperature=temperature or 0.8,
    )
    return response.choices[0].message.content


LANG_MAP = {
    "python": "main.py",
    "py": "main.py",
    "bash": "run.sh",
    "shell": "run.sh",
    "yaml": "config.yaml",
    "yml": "config.yaml",
    "json": "config.json",
    "toml": "pyproject.toml",
    "text": "README.md",
    "markdown": "README.md",
    "md": "README.md",
    "dockerfile": "Dockerfile",
    "gitignore": ".gitignore",
    "ini": "config.ini",
    "cfg": "setup.cfg",
}


def parse_code_blocks(content):
    blocks = []
    pattern = r"```(\w+(?:\.\w+)?)\n(.*?)```"
    matches = re.findall(pattern, content, re.DOTALL)
    file_counter = 0
    for tag, code in matches:
        code = code.strip()
        if not code:
            continue
        filename = tag if "." in tag else LANG_MAP.get(tag)
        if not filename:
            file_counter += 1
            filename = f"module_{file_counter}.py" if "python" in content[:content.find(f"```{tag}") + len(tag) + 100].lower() else f"file_{file_counter}.txt"
        blocks.append({"filename": filename, "code": code})
    return blocks


def write_project_files(project_path, content):
    project_path = Path(project_path)
    project_path.mkdir(parents=True, exist_ok=True)

    blocks = parse_code_blocks(content)

    if not blocks:
        (project_path / "main.py").write_text(content)
        return

    written = []
    for block in blocks:
        filename = block["filename"]
        if ".." in filename or filename.startswith("/"):
            continue
        filepath = project_path / filename
        filepath.parent.mkdir(parents=True, exist_ok=True)
        filepath.write_text(block["code"])
        written.append(filename)

    if not list(project_path.rglob("test_*.py")):
        test_file = project_path / "test_basic.py"
        test_file.write_text(
            "def test_placeholder():\n    assert True\n"
        )
        written.append("test_basic.py")

    return written
